### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by fresheneesz** [dougbutner/web-4#1]
> Web 4 Democratic Web

One thing I don't quite grok here is the "web 4" name. In listing out the 4 webs, you list the first three as basically ways of serving general-purpose applications. However, web 4 doesn't clearly fit that pattern. Rather than being a way of serving general-purpose applications, the most that can be said is that it is used to serve specific-use applications for voting/collaborating. It seems more like Web democratization would be a feature of web 3, rather than its own separate thing. 

> web 3 enhances the abilities of web 2

How?

> Information Entropy Information degradation over time, pseudo accounts in sensitive systems

I don't understand what you mean by "pseudo accounts" or how it relates to entropy. I don't see that term used anywhere else in the paper.

> If we try to get rid of this trust by implementing a system so good we are our own private key, it can backfire

How?

> if we built it because we were fearful instead of trusting, that's super lame.

I might revise this sentence ; ) Perhaps you mean that if we try do decrease our trust from almost zero to very nearly 0 at the expense of usability of the system, that we may be shooting ourselves in the foot?

> Geo domains

I think the geodomain and geotribe concepts are pretty easy to understand. "Geo-social" is something I found was left vague to me. I think if you moved the "What is a Geo-Social system?" section to just below "Concepts" (or put Geo-social system into concepts), it would feel less vauge later. 

I like the geodomain concept, and the stratification you write down. But it makes me wonder if its worth being a little more nuanced here. I like to think of governments within governments as separate entities that are given boundaries by their higher government. It might be worth defining that a geodomain can exist within another one, rather than defining a geodomain as a monolith that simply has stratification within it. For example, what if [a world government](https://governology.wordpress.com/2017/03/11/an-international-federation-part-1/) was created? It would be its own geodomain, no? However it (ideally) shouldn't simply become the only geodomain in the world, right? Semantics perhaps, but the semantics of the concepts could help direct how these things are thought about into a more modular and manageable form, ie where a city is just like a state, just smaller.

> It is important for every system that each individual only exist within one geotribe (excluding those extrapolated) so that their vote isn't counted twice.

This is hard for me to understand. First of all, I assume by "system" you mean geo-social system (it might be helpful to fully quality it here still). But also, I don't follow the concept of extrapolating one's geotribe. Is this basically just saying that a person can only be part of one geodomain? What about dual citizens? Would you have a different concept for people following rules in geo-social systems they aren't a resident of at the moment? I think it might be important to clarify that kind of thing.

I could imagine, for example, that a geodomain could be defined as a bounded area that defines rules for people that apply when those people are in that area. Those rules might include conditions about things that happen *outside* that geodomain, however the rules would only generally be enforceable when that person is inside that geodomain. So, for example, there might be a rule that says "you have to pay X taxes to remain a citizen of G geodomain", such that if you don't no matter where you are, when you try to reenter, you will no longer have the priviliges of a citizen. Since real countries do that kind of thing, its important for this design to be able to model that.

Because of the above issues, I would recommend removing the restriction that people only be part of one geodomain. It might be more flexible to simply remove the concept of geotribe, and simply use the concept that a geodomain has rules that apply to people. If you have geodomains inside geodomains, this should work pretty well, since each geodomain would essentially keep its own count of who get a vote. This could be especially important for situations where the larger geodomain is more permissive in representation than the narrower geodomain. For example, were a world government to come about, its possible the world government would do something like allow all prisoners to vote, whereas in many countries prisoners cannot vote. It would make sense to model this where the "world" geodomain has rules on who gets a vote that are broader/different than any given sub geodomain. 

> only the deepest level of association is needed

Needed for what? This is also not clear to me, probably because the extrapolation part is still not clear to me. 

> They may vote all 12 tokens for an initiative they are most passionate about

I understand this is only an example, but that would seem to be a broken system. There would be edge cases where issues that are 13th-15th on people's list get decided in odd ways by the people for which they were higher on the list. In other words, the people for whom an issue is within the top 12 issues they care about may not be a group that's representative of the whole. Would be better to give everyone 1 token for every issue that can be voted on. 

> Information entropy ... could make a person's (anonymous) voting record less knowable over time by increasing the amount of CPU time needed to associate one vote with another.

I feel like this probably doesn't hold water. When information becomes public on the internet, it can't really be expected to become un-public. So if there were some system where its harder to extract older information, that information will simply be extracted as soon as possible and copied to somewhere that doesn't have that property.

The rest of this are basically my opinions and thoughts about your ideas rather than a critique of the writing.

> Biometrics

So the problem with biometrics is that its not really secret. Anyone can measure your biometrics. Fingerprint? You can take a picture of it. Iris? Same thing. DNA? Even easier to obtain. Biometrics aren't very secret. 

Now, you could have a situation where you require special equiptment that takes this biometric data in a particular way. If you know that equipment was used and used properly, then you can know the biometric data is accurate. However, you can't examine remotely the data emitted by such hardware and determine whether its legit, because you can't actually know that hardware created it remotely. 

I view it as along the same lines as an encryption key vs a website password. With encrypted data, you can brute force encryption keys as fast as your computer can operate. By contrast, with a website, the owner of the website knows that the password is being evaluated on their hardware. They can limit how often the password can be checked for validity. So even if someone has a super computer, they can't get into a properly secured website because they're limited to testing a password once per second, or 5 times per minute, or something like that. 

With biometrics, its kind of worse. You only know its valid if you know what hardware is doing the validation (ie generating the validation data from your actual body). And even then, you need to make the hardware such that it can't be fooled. A standard camera scanning your face won't cut it. 

>  biometric expressions (used to make a biokey) must be unique (for example, which combination of words to speak)

This just sounds like a password with more steps. Why not just remember a secure passphrase at that point? Are the biometrics really giving you extra security?

> The upside of biosecrets is they cannot be lost

I'm not sure that's really true. If part of your biosecrets is things you remember, you can absolutely lose them, just like you can forget a password. Also, biometrics that match expressions and facial structures can fail if you have a disease, brain injury, accident, etc.

> In a web 4 ecosystem, where the tokens are distributed daily and often spent daily, a hack would be much less catastrophic. 

This is actually quite comforting. It won't help me quiet my nerves about my bitcoin wallet, but it is heartening to realize that with time tokens, the damage and attack can do is minimal. However this does imply there is some way to change your biometrics after an attack. What would you change them with in a truely decentralized system? If you can use your current biometrics to change what biometrics/biosecrets you use, can't the attacker do the same? Perhaps this would be kind of a multisig scenario where you can use your web 4.0 applications with just one biometric/biosecret, but to update your biometrics, you need to validate all (of many) of your biosecrets. Without something like this, there would need to be some centralized entity that can reset you. 

>  the equality of each human being.

I don't think I quite agree that this is a quality of nature. The equality of humans is something that I certainly think works best for us, but it requires constant vigillence against those that would prevent equality. It requires governments to enforce that equality. 

> Democracy ... has become too slow to keep up with the modern world

In my personal opinion, I would characterize this differently. I think democracies of the world are getting old, and while at the start they had the people's inerests in mind, they have been corrupted by perverse incentives that have caused decreasing quality (accuracy) of representation of the people. Democracy is supposed to be slow. Just like cryptocurrency consensus, it takes time for many separated people/entities to come to an agreement about the state of the world and what it should be. The problem is twofold, that 1. people generally expect too much from government - they expect government to do too much, so it can't keep up with demand (whether created by people or by politicians). And 2. Many democracies have fallen into a two party trap, where the parties are constantly trying to shut down the other. This of course slows things as well, because agreement isn't the goal, dominance is. 

So I would say democracy has become inefficient and unrepresentative. I always wince when people say things like "finally congress will be able to get things done". The thing is, we shouldn't want government to "get things done". We should want them to get things right in the first place so we don't have to expect them to rush shoddy laws through in the futile hopes of them fixing things at the last minute. Laws should be well thought through and well curated. Having a legal system with more legal code than any human could read in their lifetime is the equivalent of a programmer trying to make progress in a 300 year old code base written in COBOL.

**Comment by dougbutner** [comment]
Thank you for your feedback, it's super valuable to me now and to everyone reading in the future. I apologize for the lapse in reply. This paper had been too much in-focus to me, so I pushed it to the side to focus back on cXc Music dev. 

I fixed a lot of the going through, but will update it more to submit it back to the "peers" (aka reddit) when ready. 


> the most that can be said is that it is used to serve specific-use applications for voting/collaborating

Action Point: Do a better job communicating the use cases of Time Tokens [Working]


> I don't understand what you mean by "pseudo accounts" or how it relates to entropy. I don't see that term used anywhere else in the paper.

I removed this concept out of the paper. Missed changing this, thanks. [Fixed]


Also added "This difficulty may be overcame with resources or tokens required to execute a smart contract." to clarify the posited use of this idea. 


>It might be worth defining that a geodomain can exist within another one, rather than defining a geodomain as a monolith that simply has stratification within it.

I changed the wording to make it more simple. You were right it was badly worded. [Fixed]

> But also, I don't follow the concept of extrapolating one's geotribe. Is this basically just saying that a person can only be part of one geodomain?

Meaning at each level you can be on one, so you couldn't belong to two states at the same time, or two countries. But every level you should belong at one, and the deepest level allows each other level to be known. I hadn't thought about allowing a person to be from one city but a different state, but it would be possible. 

I meant that when you have the most detailed level the others are known by the sets they belong to. You are from NYC? I know the state, nation, county, etc.

Again, I updated the wording in the paper here [Fixed]

>When using stratified geodomains, such as geopolitically-based ones, only the deepest level of association is needed (city/community), from which the rest can be extrapolated.


> I feel like this probably doesn't hold water. When information becomes public on the internet, it can't really be expected to become un-public. So if there were some system where its harder to extract older information, that information will simply be extracted as soon as possible and copied to somewhere that doesn't have that property.

The information is public, so increasing required resources to accessing it may not make sense as a disincentive. It would make sense as a cost to interact with a smart contract that expresses relation to the time units. This could be by requiring more tokens to interact with a smart contract over time. 

An example would be publish a specification that allows the user to declare a price increase in th price of running a specific contract. 
A use case of this feature would be to use a service that generates NFTs. User makes a NFT on day one, it's 1 token, then every day the price raises by 1 token, etc.

> , the people for whom an issue is within the top 12 issues they care about may not be a group that's representative of the whole. 

Always seems to be the case. In Effective we use 144, so perhaps that's a little better (or worse), but it is a big concern for me too, though I know it's far off from implementation. It's worth developing a better system sooner, let me know if you have ideas for that one. The best I thought of was making lists a popular thing to publish so "lazy" voters can entrust someone more devoted to knowing what to fund (akin to elected leader in rep dem).


>Would be better to give everyone 1 token for every issue that can be voted on.

What you say makes if there is a decision. It's possible to build like that, the token could even be. I am thinking of a different use case (EC) where everyone gets funded after a level of funding, but the funding is system-granted (minted), and directed by the votes of the people.



> What would you change them with in a truely decentralized system? If you can use your current biometrics to change what biometrics/biosecrets you use, can't the attacker do the same? Perhaps this would be kind of a multisig scenario where you can use your web 4.0 applications with just one biometric/biosecret, but to update your biometrics, you need to validate all (of many) of your biosecrets. Without something like this, there would need to be some centralized entity that can reset you.

That's a good point which I hadn't considered because I thought the user's real biometric data wouldn't change, but you would have to have some sort of a fallback. I don't plan to build apps with biometrics personally. 



> Laws should be well thought through and well curated. Having a legal system with more legal code than any human could read in their lifetime is the equivalent of a programmer trying to make progress in a 300 year old code base written in COBOL.

I agree, and am optimistic this is very feasible on-chain. I also think there should be a shelf life of a law, after which it must go to vote again to remain in effect, perhaps every decade.

**Comment by fresheneesz** [comment]
> It's worth developing a better system sooner, let me know if you have ideas for that one. The best I thought of was making lists a popular thing to publish so "lazy" voters can entrust someone more devoted to knowing what to fund (akin to elected leader in rep dem).

In Liquid Democracy, any voter can specify another individual to give their vote to for any given issue, category of issues, or all issues. I think this is a very elegant way to solve the "lazy voter" problem. The laziest of voters can just simply give their vote to someone else. Voters who care about one category of things but not most things can give their vote away for most categories of proposals but reserve it for the category they care about. And voters who want to vote on everything can do that. Its probably simplest to simply have voters specify someone to proxy their vote to in the case they don't vote themselves (if they want) - which avoids people having to specify categories beforehand. But the categories thing would be useful if they want to proxy their vote to different people depending on the category of the referrendum at hand.

**Comment by fresheneesz** [comment]
>  I am thinking of a different use case (EC) where everyone gets funded after a level of funding, but the funding is system-granted (minted), and directed by the votes of the people.

Why not give people an amount of funding to allocate, and they can split it up as granularly as they like? This is as opposed to using some number of tokens (12?) that each represent a chunk of funding. 

> I agree, and am optimistic this is very feasible on-chain. I also think there should be a shelf life of a law, after which it must go to vote again to remain in effect, perhaps every decade.

I agree. And [Elon agrees too](https://twitter.com/elonmusk/status/1008124944289370113?lang=en).
